spring:
  profiles:
    active: prod
  application:
    name: adventofcode
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: customer
    password: customer
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

my:
  properties:
    url: https://www.xavierbouclet.com
    activated: true
    timeout: 3000


management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoint:
    info:
      access: unrestricted
    health:
      access: read_only
    loggers:
      access: unrestricted
    metrics:
      access: unrestricted

  endpoints:
    web:
      exposure:
        include: loggers,info,health,metrics
  defaults:
    metrics:
      export:
        enabled: true

info:
  app:
    name: Advent of Code
    description: A sample Spring Boot application for day 19 of Advent of Spring Boot
    version: 1.0.0
  dev:
    name: Xavier Bouclet
  blog:
    name: https://www.xavierbouclet.com

