spring:
  profiles:
    active: prod
  application:
    name: adventofcode
  cache:
    cache-names: "productById"
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: customer
    password: customer
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

my:
  properties:
    url: https://www.xavierbouclet.com
    activated: true
    timeout: 3000


management:
  info:
    java:
      enabled: true
    env:
      enabled: true
  endpoint:
    info:
      access: read_only
    loggers:
      access: unrestricted
    metrics:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include: health,info,loggers,metrics

info:
  app:
    name: Advent of Code
    description: A Spring Boot app for DAY 19 of Advent of Spring Boot
  dev:
    name: Xavier Bouclet
  blog:
    url: https://www.xavierbouclet.com

